{{ config(materialized='table', schema='FINAL') }}

SELECT
    TRIP_DATE,
    COUNT(*) AS TOTAL_TRIPS,
    ROUND(AVG(TRIP_DISTANCE), 2) AS AVG_DISTANCE,
    ROUND(SUM(TOTAL_AMOUNT), 2) AS TOTAL_REVENUE,
    ROUND(AVG(TIP_PCT), 2) AS AVG_TIP_PCT,
    ROUND(AVG(TRIP_DURATION_MIN), 2) AS AVG_DURATION_MIN
FROM {{ ref('stg__clean_trips') }}
GROUP BY TRIP_DATE
ORDER BY TRIP_DATE
