{{ config(materialized='table', schema='FINAL') }}

SELECT
    PICKUP_HOUR,
    TRIP_DATE,
    COUNT(*) AS TOTAL_TRIPS,
    ROUND(SUM(TOTAL_AMOUNT), 2) AS TOTAL_REVENUE,
    ROUND(AVG(TRIP_DISTANCE), 2) AS AVG_DISTANCE,
    ROUND(AVG(TRIP_DURATION_MIN), 2) AS AVG_DURATION_MIN,
    ROUND(AVG(TIP_PCT), 2) AS AVG_TIP_PCT
FROM {{ ref('stg__clean_trips') }}
GROUP BY PICKUP_HOUR, TRIP_DATE
ORDER BY PICKUP_HOUR, TRIP_DATE
