{{ config(materialized='table', schema='STAGING') }}

WITH source AS (
    SELECT * FROM {{ source('RAW', 'YELLOW_TAXI_TRIPS_V2') }}
),

cleaned AS (
    SELECT
        VENDORID,
        TPEP_PICKUP_DATETIME,
        TPEP_DROPOFF_DATETIME,
        DATEDIFF('minute', TPEP_PICKUP_DATETIME, TPEP_DROPOFF_DATETIME) AS TRIP_DURATION_MIN,
        TRIP_DISTANCE,
        TOTAL_AMOUNT,
        TIP_AMOUNT,
        FARE_AMOUNT,
        ROUND((TIP_AMOUNT / NULLIF(FARE_AMOUNT, 0)) * 100, 2) AS TIP_PCT,
        PULOCATIONID,
        DOLOCATIONID,
        PASSENGER_COUNT,
        CAST(PAYMENT_TYPE AS VARCHAR) AS PAYMENT_TYPE,
        CAST(RATECODEID AS INTEGER) AS RATECODEID,
        MTA_TAX,
        EXTRA,
        TOLLS_AMOUNT,
        IMPROVEMENT_SURCHARGE,
        CONGESTION_SURCHARGE,
        AIRPORT_FEE,
        -- Temporal dimensions
        DATE(TPEP_PICKUP_DATETIME) AS TRIP_DATE,
        HOUR(TPEP_PICKUP_DATETIME) AS PICKUP_HOUR,
        MONTH(TPEP_PICKUP_DATETIME) AS PICKUP_MONTH
    FROM source
    WHERE TOTAL_AMOUNT >= 0
      AND TRIP_DISTANCE BETWEEN 0.1 AND 100
      AND TPEP_DROPOFF_DATETIME > TPEP_PICKUP_DATETIME
      AND PULOCATIONID IS NOT NULL
      AND DOLOCATIONID IS NOT NULL
      AND PASSENGER_COUNT BETWEEN 1 AND 6
)

SELECT * FROM cleaned
