name: 'nyc_taxi_dbt_snowflake'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi_dbt_snowflake'

model-paths: ["models"]
target-path: "target"

models:
  nyc_taxi_dbt_snowflake:
    raw:
      +schema: raw
      +materialized: view
    staging:
      +schema: staging
      +materialized: table
    final:
      +schema: final
      +materialized: table
