name: 'nyc_taxi_dbt_snowflake'
version: '1.0.0'
config-version: 2

profile: 'nyc_taxi_dbt_snowflake'

model-paths: ["models"]
seed-paths: ["seeds"]
target-path: "target"

models:
  nyc_taxi_dbt_snowflake:
    raw:
      +schema: RAW
      +materialized: view
    staging:
      +schema: STAGING
      +materialized: table
    final:
      +schema: FINAL
      +materialized: table
  dbt_project_evaluator:
    +schema: PROJECT_EVALUATOR
    +materialized: table

seeds:
  nyc_taxi_dbt_snowflake:
    +schema: STAGING

vars:
  dbt_project_evaluator:
    # Seuils de couverture (0-100)
    documentation_coverage_target: 0   # On part de 0 pour voir l'état réel
    test_coverage_target: 0            # Idem — on monte progressivement
