name: Full ETL + dbt Pipeline

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  python_etl:
    name: Run Python ETL (Download + Ingest)
    runs-on: ubuntu-latest

    env:
      SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure log & data folders exist
        run: |
          mkdir -p logs
          mkdir -p extract/data
          mkdir -p load/verifications

      - name: Run Python ETL
        run: |
          python extract/download_parquet.py
          python load/merge_dynamic.py

  dbt:
    name: Run dbt Pipeline
    runs-on: ubuntu-latest
    needs: python_etl  # Attend la fin du job ETL

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dbt and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-snowflake pandas snowflake-connector-python

      - name: Create dbt profiles.yml
        run: |
          mkdir -p ~/.dbt
          cat <<EOF > ~/.dbt/profiles.yml
          nyc_taxi_dbt_snowflake:
            target: dev
            outputs:
              dev:
                type: snowflake
                account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
                user: ${{ secrets.SNOWFLAKE_USER }}
                password: ${{ secrets.SNOWFLAKE_PASSWORD }}
                role: ACCOUNTADMIN
                warehouse: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
                database: ${{ secrets.SNOWFLAKE_DATABASE }}
                schema: ${{ secrets.SNOWFLAKE_SCHEMA }}
                threads: 1
                client_session_keep_alive: False
            EOF
      
                  
          
      - name: Run dbt
        working-directory: ./nyc_taxi_dbt_snowflake
        run: |
          dbt deps --profiles-dir ~/.dbt
          dbt seed --full-refresh
          dbt run --profiles-dir ~/.dbt
          dbt test --profiles-dir ~/.dbt